test:
	make CBV.cpp
	make Identity.test
	make Errors.test
	make Positions.test
	make State.test
	make Output.test
	make Nondeterminism.test
	make Backwards.test
	make Callcc.test

include ../Makefile.include
