test:
	make Baseline.test
	make Patch.test
	make CBV.cpp
	make Identity.test
	make Errors.test
	make Positions.test
	make State.test
	make Output.test
	make Nondeterminism.test
	make Backwards.test
	make CBN.cpp
	make StateCBN.test
	make NondeterminismCBN.test
	make CPS.test
	make Callcc.test
	make ErrorsCPS.test
	make StateCPS.test

include ../Makefile.include

